# MIT License

# Copyright (c) 2020-2021 Chris Farris (https://www.chrisfarris.com)

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

AWSTemplateFormatVersion: '2010-09-09'
Description: Stands up Central ALB for ECommerce API

Parameters:

  pVpcId:
    Description: VPCId to deploy the ALB
    Type: String

  pFQDN:
    Description: Fully Qualified Domain Name for this ALB (gets registered in Route53)
    Type: String

  pCertificateArn:
    Description: Arn of the wildcard cert in ACM
    Type: String

  pSubnet1:
    Type: AWS::EC2::Subnet::Id

  pSubnet2:
    Type: AWS::EC2::Subnet::Id

  pWAFArn:
    Type: String
    Description: Arn of the WAF to attach to the ALB
    Default: None

  pTeamNumber:
    Type: String
    Description: Unique number for the team

  pTeamPath:
    Type: String
    Description: Unique HTTP URI path for the team

  pTargetIP:
    Type: String
    Description: Internal IP of the HAProxy in the team VPC

  pPublicZoneId:
    Description: Hosted Zone ID of the Public HostedZoneId - created by Corporate VPC
    Type: String

  pPrivateZoneId:
    Description: Hosted Zone ID of the Private HostedZoneId - created by Corporate VPC
    Type: String

  pServerAZ:
    Description: AZ where the Server Subnet Lives
    Type: String


Conditions:
  cAttachWAF: !Not [ !Equals [ !Ref pWAFArn, "None" ] ]

Resources:

  ECommLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Ref AWS::StackName
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - !Ref pSubnet1
        - !Ref pSubnet2
      Type: application

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref pVpcId
      GroupDescription: !Sub "Generated by the ${AWS::StackName}"
      GroupName: !Sub "${AWS::StackName}-SecurityGroup"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"
          Description: "Added by Cloudformation at stack create"
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: "0.0.0.0/0"
          Description: "Added by Cloudformation at stack create"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-SecurityGroup"

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref pCertificateArn
      DefaultActions:
        # The Default Action is to forward everything to the TargetGroup
        - Type: forward
          TargetGroupArn: !Ref TeamAPITargetGroup
      LoadBalancerArn: !Ref ECommLoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-FS-1-2-Res-2019-08

  PublicRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref pPublicZoneId
      Name: !Ref pFQDN
      ResourceRecords:
        - !GetAtt ECommLoadBalancer.DNSName
      TTL: 60
      Type: CNAME

  PrivateRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref pPrivateZoneId
      Name: !Ref pFQDN
      ResourceRecords:
        - !GetAtt ECommLoadBalancer.DNSName
      TTL: 60
      Type: CNAME

  WAFAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Condition: cAttachWAF
    Properties:
      ResourceArn: !Ref ECommLoadBalancer
      WebACLArn: !Ref pWAFArn

  TeamAPIListenerRule:
    # This may no longer be needed since the Default Action is to forward to TargetGroup.
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Order: 1
          TargetGroupArn: !Ref TeamAPITargetGroup
          Type: forward
      Conditions:
        - Field: path-pattern
          Values:
            - "/*"
            # - !Sub "/${pTeamPath}/*"
      ListenerArn: !Ref HTTPSListener
      Priority: !Ref pTeamNumber

  TeamAPITargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref AWS::StackName
      Port: 80
      Protocol: HTTP
      Targets:
        - Id: !Ref pTargetIP
          AvailabilityZone: !Ref pServerAZ
          Port: 80
      TargetType: ip
      VpcId: !Ref pVpcId


Outputs:

  StackName:
    Value: !Ref 'AWS::StackName'

  ALBDNSName:
    Value: !GetAtt ECommLoadBalancer.DNSName

  APIDNSName:
    Value: !Sub "https://${pFQDN}"

